<a href="https://colab.research.google.com/github/carlotagifre/Wheretowatch/blob/wheretowatch/where_to_watch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
imdb_movies=pd.read_csv('/IMDb movies.csv')
#dropped unrelated columns & unimportant columns with a lot of missing values(writer,director)
imdb_movies.drop(['budget','usa_gross_income','metascore','worlwide_gross_income','production_company','reviews_from_users','reviews_from_critics','writer','director','date_published','original_title'],axis=1,inplace=True)
#dropped all missing values from these columns so there's no missing values
imdb_movies.dropna(subset=['description','language','country','actors'],inplace=True)
imdb_movies=imdb_movies[imdb_movies["language"].str.contains("None")==False]
imdb_movies=imdb_movies.astype({'title': 'object', 'year': 'int64', 'genre':'object','duration':'int64','country':'object','language':'object','actors':'object'
,'description':'object','avg_vote':'float64','votes':'int64','imdb_title_id':'object'})
pd.set_option('display.max_rows',None)


imdb_movies=imdb_movies.loc[imdb_movies['language'].str.contains("English|French|Spanish|Italian|German|Turkish", case=False)]
language=imdb_movies['language'].value_counts()
imdb_movies=imdb_movies.loc[imdb_movies['genre'].str.contains("Comedy|Drama|Romance|Action|Horror|Thriller", case=False)]
genre=imdb_movies['genre'].value_counts()

In [5]:
imdb_ratings=pd.read_csv('/IMDb ratings.csv')
imdb_ratings=imdb_ratings.dropna()

In [13]:
wheretowatch=pd.merge(imdb_movies,imdb_ratings,on='imdb_title_id')
wheretowatch.head(5)

  imdb_title_id  ... non_us_voters_votes
0     tt0002130  ...              1166.0
1     tt0003740  ...              1332.0
2     tt0006206  ...              1945.0
3     tt0006864  ...              5954.0
4     tt0010323  ...             25399.0

[5 rows x 59 columns]